services:
  - type: web
    name: disaster-reporting-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0